#' Cached ADSL
#'
#' Cached ADSL data
#'
#' @docType data
#'
#' @usage data(eg_adsl)
"eg_adsl"

#' Cached ADMH
#'
#' Synthetic Medical History Analysis Dataset generated from [`eg_adsl`] with
#' `random.cdisc.data::radmh()` version 0.3.16 and seed 130. It contains one or
#' more medical-history records for 356 of the 400 example subjects. Subjects
#' without medical history remain in ADSL for population denominators.
#'
#' Important columns include subject and study identifiers (`USUBJID`,
#' `STUDYID`), treatment (`TRT01A`), body system and decoded term (`MHBODSYS`,
#' `MHDECOD`), sequence (`MHSEQ`), and analysis start date/time (`ASTDTM`).
#'
#' @docType data
#'
#' @format A data frame with 1,919 rows and 68 columns, generated by `data-raw/eg_admh.R`.
#' @md
#' @source Synthetic data generated by the public
#'   [random.cdisc.data](https://insightsengineering.github.io/random.cdisc.data/)
#'   package; see `data-raw/eg_admh.R` for the reproducible recipe.
#' @usage data(eg_admh)
"eg_admh"

#' Cached ADAE
#'
#' Cached ADAE data
#'
#' @docType data
#'
#' @usage data(eg_adae)
"eg_adae"

#' Cached ADTTE
#'
#' Cached ADTTE data
#'
#' @docType data
#'
#' @usage data(eg_adtte)
"eg_adtte"

#' Cached ADEX
#'
#' Cached ADEX data
#'
#' @docType data
#'
#' @usage data(eg_adex)
"eg_adex"

#' Cached ADEG
#'
#' Cached ADEG data
#'
#' @docType data
#'
#' @usage data(eg_adeg)
"eg_adeg"

#' Cached ADVS
#'
#' Cached ADVS data
#'
#' @docType data
#'
#' @usage data(eg_advs)
"eg_advs"

#' Cached ADLB
#'
#' Cached
#' ADLB data
#'
#' @docType data
#'
#' @usage data(eg_adlb)
"eg_adlb"

#' Cached ADRS
#'
#' Cached ADRS data
#'
#' @docType data
#'
#' @usage data(eg_adrs)
"eg_adrs"


#' Cached ADTR
#'
#' Cached ADTR data
#'
#' @docType data
#'
#' @usage data(eg_adtr)
"eg_adtr"


#' Cached trial
#'
#' Cached trial data
#'
#' @docType data
#'
#' @export
trial <- gtsummary::trial
